name: galapagos
channels:
  - conda-forge
  - bioconda
  - qiime2
  - defaults
dependencies:
  - r-cluster=2.1.0
  - r-rprojroot=1.3_2
  - r-zeallot=0.1.0
  - r-desc=1.2.0
  - r-rcurl=1.98_1.2
  - r-data.table=1.12.8
  - r-lifecycle=0.2.0
  - r-magrittr=1.5
  - r-formatr=1.7
  - r-mass=7.3_51.6
  - r-fansi=0.4.1
  - r-pkgbuild=1.0.7
  - r-hwriter=1.3.2
  - r-testthat=2.3.2
  - r-vegan=2.5_6
  - r-matrix=1.2_18
  - r-processx=3.4.2
  - r-ellipsis=0.3.0
  - r-scales=1.1.0
  - r-futile.logger=1.4.3
  - r-rlang=0.4.5
  - r-crayon=1.3.4
  - r-praise=1.0.0
  - r-callr=3.4.3
  - r-withr=2.2.0
  - r-farver=2.0.3
  - r-lambda.r=1.2.4
  - r-gtable=0.3.0
  - r-prettyunits=1.1.1
  - r-stringi=1.4.6
  - r-bh=1.72.0_3
  - r-plyr=1.8.6
  - r-nlme=3.1_147
  - r-rstudioapi=0.11
  - r-pkgconfig=2.0.3
  - r-ps=1.3.2
  - r-pillar=1.4.3
  - r-glue=1.4.0
  - r-digest=0.6.25
  - r-rcolorbrewer=1.1_2
  - r-tibble=3.0.1
  - r-stringr=1.4.0
  - r-labeling=0.3
  - r-assertthat=0.2.1
  - r-lattice=0.20_41
  - r-vctrs=0.2.4
  - r-rcppparallel=5.0.0
  - r-permute=0.9_5
  - r-bitops=1.0_6
  - r-pkgload=1.0.2
  - r-backports=1.1.6
  - r-munsell=0.5.0
  - r-mgcv=1.8_31
  - r-latticeextra=0.6_28
  - r-ggplot2=3.3.0
  - r-snow=0.4_3
  - r-colorspace=1.4_1
  - r-base=3.5.1
  - r-futile.options=1.0.1
  - r-reshape2=1.4.4
  - r-r6=2.4.1
  - r-matrixstats=0.56.0
  - r-cli=2.0.2
  - r-isoband=0.2.1
  - r-viridislite=0.3.0
  - r-evaluate=0.14
  - r-rcpp=1.0.4.6
  - r-utf8=1.1.4
  - q2-fragment-insertion=2020.8.0
  - q2-feature-classifier=2020.8.0
  - q2cli=2020.8.0
  - q2templates=2020.8.0
  - q2-metadata=2020.8.0
  - q2-types=2020.8.0
  - q2-diversity-lib=2020.8.0
  - q2-alignment=2020.8.0
  - q2-emperor=2020.8.0
  - q2-feature-table=2020.8.0
  - q2-dada2=2020.8.0
  - q2-gneiss=2020.8.0
  - q2-quality-control=2020.8.0
  - qiime2=2020.8.0
  - q2-sample-classifier=2020.8.0
  - q2-composition=2020.8.0
  - q2-longitudinal=2020.8.0
  - q2-taxa=2020.8.0
  - q2-deblur=2020.8.0
  - q2-cutadapt=2020.8.0
  - q2-demux=2020.8.0
  - q2-diversity=2020.8.0
  - q2-phylogeny=2020.8.0
  - q2-quality-filter=2020.8.0
  - q2-vsearch=2020.8.0
  - itsxpress
