name: qiime2-2020.8
channels:
  - qiime2
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - urllib3=1.25.10
  - ipython_genutils=0.2.0
  - matplotlib=3.2.2
  - typing_extensions=3.7.4.2
  - bioconductor-iranges=2.16.0
  - perl-exporter-tiny=1.002001
  - glib=2.65.0
  - r-cluster=2.1.0
  - isl=0.22.1
  - pandocfilters=1.4.2
  - readline=8.0
  - cachecontrol=0.12.6
  - q2-feature-classifier=2020.8.0
  - clangxx=9.0.1
  - r-rprojroot=1.3_2
  - bzip2=1.0.8
  - perl-parent=0.236
  - bioconductor-rsamtools=1.34.0
  - perl-list-moreutils-xs=0.428
  - q2cli=2020.8.0
  - r-zeallot=0.1.0
  - bioconductor-summarizedexperiment=1.12.0
  - lcms2=2.11
  - q2templates=2020.8.0
  - perl-types-serialiser=1.0
  - xopen=0.9.0
  - perl-scalar-list-utils=1.52
  - networkx=2.4
  - perl-digest-hmac=1.03
  - perl-http-message=6.18
  - ipykernel=5.3.4
  - openssl
  - prometheus_client=0.8.0
  - harfbuzz=2.4.0
  - scikit-bio=0.5.5
  - perl-file-listing=6.04
  - r-desc=1.2.0
  - perl-html-parser=3.72
  - lockfile=0.12.2
  - q2-metadata=2020.8.0
  - notebook=6.1.3
  - r-rcurl=1.98_1.2
  - r-data.table=1.12.8
  - q2-types=2020.8.0
  - raxml=8.2.12
  - jpeg=9d
  - perl-compress-raw-zlib=2.087
  - r-lifecycle=0.2.0
  - r-magrittr=1.5
  - perl=5.26.2
  - argon2-cffi=20.1.0
  - dendropy=4.4.0
  - r-formatr=1.7
  - packaging=20.4
  - pillow=7.2.0
  - r-mass=7.3_51.6
  - bioconductor-genomeinfodbdata=1.2.1
  - mafft=7.471
  - libllvm9=9.0.1
  - bwidget=1.9.14
  - pyzmq=19.0.2
  - entrez-direct=13.3
  - nose=1.3.7
  - prompt-toolkit=3.0.6
  - requests=2.24.0
  - perl-xml-sax=0.99
  - q2-diversity-lib=2020.8.0
  - seaborn-base=0.10.1
  - python_abi=3.6
  - python=3.6.11
  - perl-lwp-protocol-https=6.07
  - python-dateutil=2.8.1
  - libarbdb=6.0.6
  - entrypoints=0.3
  - statsmodels=0.11.1
  - mpfr=4.0.2
  - gfortran_impl_osx-64=7.5.0
  - cryptography=3.0
  - make=4.3
  - r-fansi=0.4.1
  - seaborn=0.10.1
  - perl-xml-namespacesupport=1.12
  - r-pkgbuild=1.0.7
  - perl-exporter=5.72
  - liblapacke=3.8.0
  - r-hwriter=1.3.2
  - hmmer=3.1b2
  - q2-alignment=2020.8.0
  - webencodings=0.5.1
  - bioconductor-biocgenerics=0.28.0
  - jupyter_client=6.1.6
  - r-testthat=2.3.2
  - perl-http-daemon=6.01
  - r-vegan=2.5_6
  - libwebp-base=1.1.0
  - perl-lwp-mediatypes=6.04
  - natsort=7.0.1
  - emperor=1.0.1
  - r-matrix=1.2_18
  - tornado=6.0.4
  - clangxx_osx-64=9.0.1
  - bioconductor-genomicalignments=1.18.1
  - iniconfig=1.0.1
  - libxml2=2.9.10
  - psutil=5.7.2
  - r-processx=3.4.2
  - q2-emperor=2020.8.0
  - pango=1.42.4
  - r-ellipsis=0.3.0
  - r-scales=1.1.0
  - perl-http-negotiate=6.01
  - pyparsing=2.4.7
  - r-futile.logger=1.4.3
  - fontconfig=2.13.1
  - r-rlang=0.4.5
  - bioconductor-s4vectors=0.20.1
  - compiler-rt=9.0.1
  - perl-io-compress=2.087
  - decorator=4.4.2
  - idna=2.10
  - backcall=0.2.0
  - r-crayon=1.3.4
  - perl-list-moreutils=0.428
  - q2-feature-table=2020.8.0
  - libtiff=4.1.0
  - q2-dada2=2020.8.0
  - perl-digest-md5=2.55
  - ijson=3.1.1
  - r-praise=1.0.0
  - pip=20.2.2
  - vsearch=2.7.0
  - gsl=2.5
  - r-callr=3.4.3
  - dnaio=0.4.2
  - bioconductor-genomeinfodb=1.18.1
  - perl-xml-simple=2.25
  - pytest=6.0.1
  - libopenblas=0.3.10
  - perl-io-socket-ssl=2.066
  - perl-json-xs=2.34
  - perl-http-cookies=6.04
  - unifrac=0.10.0
  - perl-compress-raw-bzip2=2.087
  - r-withr=2.2.0
  - perl-encode-locale=1.05
  - jupyter_core=4.6.3
  - perl-xsloader=0.24
  - samtools=1.7
  - perl-extutils-makemaker=7.36
  - libcurl=7.68.0
  - pandas=0.25.3
  - six=1.15.0
  - tk=8.6.10
  - nbformat=5.0.7
  - r-farver=2.0.3
  - pytz=2020.1
  - expat=2.2.9
  - testpath=0.4.4
  - r-lambda.r=1.2.4
  - scikit-learn=0.23.1
  - bioconductor-delayedarray=0.8.0
  - sortmerna=2.0
  - bioconductor-genomicranges=1.34.0
  - q2-gneiss=2020.8.0
  - perl-net-http=6.19
  - perl-uri=1.76
  - perl-carp=1.38
  - r-gtable=0.3.0
  - r-prettyunits=1.1.1
  - openjdk=11.0.8
  - q2-quality-control=2020.8.0
  - r-stringi=1.4.6
  - ipywidgets=7.5.1
  - threadpoolctl=2.1.0
  - ptyprocess=0.6.0
  - perl-time-local=1.28
  - hdf5=1.10.6
  - defusedxml=0.6.0
  - zipp=3.1.0
  - perl-storable=3.15
  - qiime2=2020.8.0
  - xz=5.2.5
  - bioconductor-biostrings=2.50.2
  - matplotlib-base=3.2.2
  - jedi=0.17.2
  - perl-mime-base64=3.15
  - r-bh=1.72.0_3
  - perl-encode=2.88
  - q2-sample-classifier=2020.8.0
  - pcre=8.44
  - r-plyr=1.8.6
  - msgpack-python=1.0.0
  - pyopenssl=19.1.0
  - more-itertools=8.4.0
  - gneiss=0.4.6
  - bioconductor-biobase=2.42.0
  - yaml=0.2.5
  - r-nlme=3.1_147
  - olefile=0.46
  - r-rstudioapi=0.11
  - q2-composition=2020.8.0
  - libpng=1.6.37
  - ncurses=6.2
  - perl-xml-parser=2.44_01
  - tapi=1000.10.8
  - cycler=0.10.0
  - mistune=0.8.4
  - boost-cpp=1.70.0
  - pygments=2.6.1
  - r-pkgconfig=2.0.3
  - lz4-c=1.9.2
  - attrs=20.1.0
  - r-ps=1.3.2
  - perl-io-html=1.001
  - r-pillar=1.4.3
  - perl-xml-sax-base=1.09
  - pexpect=4.8.0
  - q2-longitudinal=2020.8.0
  - r-glue=1.4.0
  - bioconductor-shortread=1.40.0
  - wcwidth=0.2.5
  - appnope=0.1.0
  - bioconductor-xvector=0.22.0
  - biom-format=2.1.8
  - nbconvert=5.6.1
  - cctools_osx-64=949.0.1
  - perl-archive-tar=2.32
  - llvm-openmp=10.0.1
  - _r-mutex=1.0.1
  - r-digest=0.6.25
  - q2-taxa=2020.8.0
  - r-rcolorbrewer=1.1_2
  - tbb=2019.9
  - perl-common-sense=3.74
  - libssh2=1.9.0
  - blas=2.17
  - cffi=1.14.1
  - q2-deblur=2020.8.0
  - r-tibble=3.0.1
  - ld64=530
  - r-stringr=1.4.0
  - libsodium=1.0.18
  - wheel=0.35.1
  - numpy=1.19.1
  - perl-libwww-perl=6.39
  - q2-cutadapt=2020.8.0
  - arb-bio-tools=6.0.6
  - pyrsistent=0.16.0
  - libgcc=4.8.5
  - r-labeling=0.3
  - kiwisolver=1.2.0
  - libcxx=10.0.1
  - ld64_osx-64=530
  - perl-pathtools=3.75
  - joblib=0.16.0
  - pandoc=2.10.1
  - perl-json=4.02
  - r-assertthat=0.2.1
  - jsonschema=3.2.0
  - bleach=3.1.5
  - r-lattice=0.20_41
  - r-vctrs=0.2.4
  - ca-certificates
  - cython=0.29.21
  - pigz=2.3.4
  - tktable=2.10
  - scipy=1.5.2
  - r-rcppparallel=5.0.0
  - r-permute=0.9_5
  - fribidi=1.0.10
  - r-bitops=1.0_6
  - clang_osx-64=9.0.1
  - h5py=2.10.0
  - q2-demux=2020.8.0
  - r-pkgload=1.0.2
  - perl-xml-sax-expat=0.51
  - gmp=6.2.0
  - r-backports=1.1.6
  - r-munsell=0.5.0
  - importlib_metadata=1.7.0
  - q2-diversity=2020.8.0
  - zstd=1.4.5
  - blast=2.9.0
  - certifi
  - r-mgcv=1.8_31
  - libgfortran=4.0.0
  - perl-html-tree=5.07
  - py=1.9.0
  - zeromq=4.3.2
  - r-latticeextra=0.6_28
  - q2-fragment-insertion=2020.8.0
  - r-ggplot2=3.3.0
  - bioconductor-dada2=1.10.0
  - q2-phylogeny=2020.8.0
  - fasttree=2.1.10
  - fastcluster=1.1.26
  - iqtree=2.0.3
  - markupsafe=1.1.1
  - click=7.1.2
  - cairo=1.16.0
  - perl-data-dumper=2.173
  - perl-business-isbn=3.004
  - q2-quality-filter=2020.8.0
  - gettext=0.19.8.1
  - send2trash=1.5.0
  - libedit=3.1.20191231
  - libblas=3.8.0
  - perl-try-tiny=0.30
  - perl-ntlm=1.09
  - importlib-metadata=1.7.0
  - liblapack=3.8.0
  - q2-vsearch=2020.8.0
  - perl-http-date=6.02
  - bioconductor-zlibbioc=1.28.0
  - compiler-rt_osx-64=9.0.1
  - perl-constant=1.33
  - toml=0.10.1
  - graphite2=1.3.13
  - sqlite=3.33.0
  - ipython=7.16.1
  - perl-mozilla-ca=20180117
  - cutadapt=2.10
  - terminado=0.8.3
  - gfortran_osx-64=7.5.0
  - perl-test-requiresinternet=0.05
  - r-snow=0.4_3
  - clang=9.0.1
  - sina=1.7.1
  - bokeh=2.1.1
  - r-colorspace=1.4_1
  - cctools=949.0.1
  - pluggy=0.13.1
  - bioconductor-biocparallel=1.16.2
  - perl-io-zlib=1.10
  - bowtie2=2.4.1
  - backports.functools_lru_cache=1.6.1
  - libcblas=3.8.0
  - tzlocal=2.1
  - perl-base=2.23
  - sepp=4.3.10
  - perl-business-isbn-data=20140910.003
  - deblur=1.1.0
  - parso=0.7.1
  - r-base=3.5.1
  - widgetsnbextension=3.5.1
  - bibtexparser=1.1.0
  - r-futile.options=1.0.1
  - hdmedians=0.13
  - freetype=2.10.2
  - chardet=3.0.4
  - perl-net-ssleay=1.88
  - zlib=1.2.11
  - pysocks=1.7.1
  - patsy=0.5.1
  - r-reshape2=1.4.4
  - perl-html-tagset=3.20
  - brotlipy=0.7.0
  - r-r6=2.4.1
  - pyyaml=5.3.1
  - r-matrixstats=0.56.0
  - r-cli=2.0.2
  - perl-www-robotrules=6.02
  - jinja2=2.11.2
  - perl-socket=2.027
  - curl=7.68.0
  - pixman=0.38.0
  - setuptools=49.6.0
  - pycparser=2.20
  - future=0.18.2
  - r-isoband=0.2.1
  - r-viridislite=0.3.0
  - pickleshare=0.7.5
  - libiconv=1.16
  - backports=1.0
  - r-evaluate=0.14
  - icu=64.2
  - mpc=1.1.0
  - krb5=1.16.4
  - traitlets=4.3.3
  - libffi=3.2.1
  - r-rcpp=1.0.4.6
  - r-utf8=1.1.4
  - itsxpress
